name: Build app
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Set gradlew permissions
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Assemble debug
        run: ./gradlew assembleDebug
